NumPy is core python library for scientific and numerical computing.

NumPy uses n-dimensional array.

Faster and efficient due to efficient memory allocation.

In [3]:
import numpy as np

NDarray: Core data structure.

In [4]:
a=np.array([1,2,3,4])
print(a,type(a))

[1 2 3 4] <class 'numpy.ndarray'>


In [5]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


Array Creation: np.array()

In [6]:
b=np.array([[1,2,3,4],[5,6,7,8]])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

Predefined arrays: np.zeros(), np.ones(), np.linespace(), np.random.rand(), np.random.randint()

In [7]:
zeroes=np.zeros((2,3),dtype="int") #default data type is float.
print(zeroes)

[[0 0 0]
 [0 0 0]]


In [8]:
ones=np.ones((2,3),dtype="int")
print(ones)

[[1 1 1]
 [1 1 1]]


In [9]:
ar=np.arange(0,10,2) # (start, end, step)
print(ar)

[0 2 4 6 8]


In [10]:
lin=np.linspace(0,10,6) #divides into parts.
print(lin)

[ 0.  2.  4.  6.  8. 10.]


In [11]:
rand=np.random.randint(2,100) #gives random integer.
rand=np.random.rand(2,3)
print(rand)

[[0.40676829 0.38534568 0.48162432]
 [0.0586513  0.60903474 0.51710063]]


Array operations

In [12]:
x=np.array([1,2,3])
y=np.array([10,20,30])

print(x+y)
print(x*y)
print(x**2)

[11 22 33]
[10 40 90]
[1 4 9]


Broadcast

In [13]:
M=np.array([[1,2,3],[4,5,6]])
V=np.array([10,20,30])
print(M+V) #values of V are added in both rows of M.

[[11 22 33]
 [14 25 36]]


Scalar Broadcasting

In [14]:
print(2*M)

[[ 2  4  6]
 [ 8 10 12]]


In [15]:
x=np.array([1,16,9])
print(np.sqrt(x))
print(np.exp(x))

[1. 4. 3.]
[2.71828183e+00 8.88611052e+06 8.10308393e+03]


Statistical Operations

In [16]:
A=np.array([[1,2,3],[4,5,6]],dtype=float)

print(A.sum())
print(A.mean())
print(A.var(),A.std())
print(A.min(),A.max())

21.0
3.5
2.9166666666666665 1.707825127659933
1.0 6.0


In [17]:
A=np.array([[1,2,3],[4,5,6]],dtype=float)
print(A.sum(axis=0)) #colomn-wise sum.

[5. 7. 9.]


In [18]:
print(A.sum(axis=1)) #row-wise sum

[ 6. 15.]


In [19]:
print(np.median(A))
print(np.percentile(A,75))

3.5
4.75


Slicing

In [20]:
D=np.arange(1,13).reshape(3,4)
print(D)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [21]:
print(D[0,0])
print(D[0,:])
print(D[:,0])
print(D[:,1])
print(D[0:2,1:3]) # row,column => only 0,1 rows are included 

1
[1 2 3 4]
[1 5 9]
[ 2  6 10]
[[2 3]
 [6 7]]


In [22]:
print(D)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Mutate the source=> change

In [23]:
sub=D[:2,:2]
sub[:]=99
print(D)

[[99 99  3  4]
 [99 99  7  8]
 [ 9 10 11 12]]


Linear Algebra Operations

In [24]:
# Dot operator of vectors.
u=np.array([1,2,3])
v=np.array([4,5,6])
print(u@v)

32


In [ ]:
# Solve Mx=b
M=np.array([[3,1],[1,2]])
b=np.array([9,8])
x=np.linalg.solve(M,b)
print(x)

[2. 3.]


In [26]:
# Inverse and determinant
Minv=np.linalg.inv(M)
detM=np.linalg.det(M)
print(Minv)
print(detM)

[[ 0.4 -0.2]
 [-0.2  0.6]]
5.000000000000001


In [ ]:
# Eigen Values and eigen vectors.
eigvals, eigvecs=np.linalg.eig(M)
print(eigvals) # array of lambda
print(eigvecs) # columns are eigenvectors.

[3.61803399 1.38196601]
[[ 0.85065081 -0.52573111]
 [ 0.52573111  0.85065081]]
